# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        # the name of the "filter set"
        main_image:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                fixed:
                    width: 255
                    height: 370
        recommended:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                fixed:
                    width: 255
                    height: 350
            # the name of the "filter set"
        slaider:
                # adjust the image quality to 75%
                quality: 75
                # list of transformations to apply (the "filters")
                filters:
                    fixed:
                        width: 104
                        height: 150

        details:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                fixed:
                    width: 255
                    height: 370