vich_uploader:
  db_driver: orm

  mappings:
    image_source:
      uri_prefix:         /images/shop
      upload_destination: '%kernel.project_dir%/public/images/shop'
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options: { property: 'slug' }

      delete_on_update: true
      delete_on_remove: true