version: '3.7'

services:
  web:
    build:
      context: ./.docker/nginx
    container_name: shop_web
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    links:
      - app
  app:
    build:
      context: ./.docker/app
    container_name: shop_app
    environment:
      PHP_IDE_CONFIG: "serverName=shop"
    volumes:
      - ./:/var/www/html
  mysql:
    build: ./.docker/mysql
    container_name: shop_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 235sdfsFGH
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306