create database shop;

CREATE USER 'dev'@'%' IDENTIFIED BY '235sdfsFGH';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON *.* TO 'dev'@'%';
FLUSH PRIVILEGES;
